apiVersion: v1
kind: Namespace
metadata:
  name: storedog
  labels:
    app.kubernetes.io/part-of: storedog-adlc-demo
    # Unified Service Tagging default env for the namespace.
    tags.datadoghq.com/env: demo
